name: Tests

on: [push, pull_request]
jobs:
    run:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['8.4', '8.5']
                composer-options: ['--ignore-platform-req=php+']
            fail-fast: false
        name: PHP ${{ matrix.php-versions }} @ ${{ matrix.operating-system }}
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  tools: 'composer:v2'
                  extensions: mbstring, posix, dom, soap
                  coverage: pcov
              env:
                  update: true
            - name: PHP info
              run: |
                  php -v
                  php -i | grep -i libxml
            - name: Install dependencies
              run: composer update --prefer-dist --no-progress --no-suggest ${{ matrix.composer-options }}
            - name: Run the tests
              run: php vendor/bin/phpunit
